version: '3'
services:

  grpcserver:
    build:
      context: ./server
    ports:
      - "50051:50051"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092

  grpcclient:
    build:
      context: ./client
    ports:
      - "8080:8080"
    depends_on:
      - grpcserver

  kafka:
    image: wurstmeister/kafka:2.12-2.5.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
