version: '3'
services:

  redis:
    image: "redis:6.2.4-alpine"
    ports:
      - "6379:6379"

  grpcserver:
    restart: always
    build:
      context: ./server
    ports:
      - "50051:50051"
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_BROKER: kafka:9092

  grpcclient:
    build:
      context: ./client
    ports:
      - "8080:8080"
    depends_on:
      - grpcserver

  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.3
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    logging:
      driver: none
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
  zookeeper_data:
