// Code generated by mockery. DO NOT EDIT.

package db

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRedisManager is an autogenerated mock type for the RedisManager type
type MockRedisManager struct {
	mock.Mock
}

type MockRedisManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisManager) EXPECT() *MockRedisManager_Expecter {
	return &MockRedisManager_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key, value
func (_m *MockRedisManager) Get(ctx context.Context, key string, value interface{}) error {
	ret := _m.Called(ctx, key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedisManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
func (_e *MockRedisManager_Expecter) Get(ctx interface{}, key interface{}, value interface{}) *MockRedisManager_Get_Call {
	return &MockRedisManager_Get_Call{Call: _e.mock.On("Get", ctx, key, value)}
}

func (_c *MockRedisManager_Get_Call) Run(run func(ctx context.Context, key string, value interface{})) *MockRedisManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockRedisManager_Get_Call) Return(_a0 error) *MockRedisManager_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisManager_Get_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockRedisManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value
func (_m *MockRedisManager) Set(ctx context.Context, key string, value interface{}) error {
	ret := _m.Called(ctx, key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisManager_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisManager_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
func (_e *MockRedisManager_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockRedisManager_Set_Call {
	return &MockRedisManager_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockRedisManager_Set_Call) Run(run func(ctx context.Context, key string, value interface{})) *MockRedisManager_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockRedisManager_Set_Call) Return(_a0 error) *MockRedisManager_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisManager_Set_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockRedisManager_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetEx provides a mock function with given fields: ctx, key, value, duration
func (_m *MockRedisManager) SetEx(ctx context.Context, key string, value interface{}, duration time.Duration) error {
	ret := _m.Called(ctx, key, value, duration)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, duration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisManager_SetEx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEx'
type MockRedisManager_SetEx_Call struct {
	*mock.Call
}

// SetEx is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - duration time.Duration
func (_e *MockRedisManager_Expecter) SetEx(ctx interface{}, key interface{}, value interface{}, duration interface{}) *MockRedisManager_SetEx_Call {
	return &MockRedisManager_SetEx_Call{Call: _e.mock.On("SetEx", ctx, key, value, duration)}
}

func (_c *MockRedisManager_SetEx_Call) Run(run func(ctx context.Context, key string, value interface{}, duration time.Duration)) *MockRedisManager_SetEx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRedisManager_SetEx_Call) Return(_a0 error) *MockRedisManager_SetEx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisManager_SetEx_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *MockRedisManager_SetEx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisManager creates a new instance of MockRedisManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisManager {
	mock := &MockRedisManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
